
name: My GITHUB Workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: zip webapp
      run: cd .. && zip -r webapp.zip webapp && cd webapp

    - name : setup env
      run : echo "DIALECT=mysql" >> ./.env

    - name: Initialize Packer Template
      run: cd packer && packer init .

    - run : npm i
    - run : npm test

    - name: validate packer
      run: cd packer && packer validate ./ami.pkr.hcl
